### ISSUE TITLE
Register as NPM

### ISSUE THREAD

**Issue by KasperAndersson** [iantearle/darksky.net-javascript-api#9]
In advance thanks

**Comment by iantearle** [comment]
@rjbultitude can you see any issues with do this? I've not registered anything on npm before - (more of a packagist for PHP developer)

**Comment by rjbultitude** [comment]
@iantearle should be fine now that it's got the UMD wrapper. I've tested it in a node app by installing it manually and it worked without any issues. 

There'll be a few hoops to jump though first though such as configuring the package.json file and setting up proper versioning. 

There's a brief set of instructions here: (https://gist.github.com/coolaj86/1318304)[https://gist.github.com/coolaj86/1318304]

**Comment by rjbultitude** [comment]
Hi @KasperAndersson 
Though this version isn't on NPM I have published a similar version here:
[npmjs.com/package/darkskyjs](https://www.npmjs.com/package/darkskyjs)
There are some breaking changes but some enhancements too. 
If you use it please read the ReadMe for details on what's changed.

**Comment by KasperAndersson** [comment]
Hi @rjbultitude,
Thank you.
